// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbikuvzeyarcmznvoxns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiaWt1dnpleWFyY216bnZveG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjEyNDIsImV4cCI6MjA2NTQ5NzI0Mn0.vvdVgdIbFKlp6bmINeXFvbDgkLZIA_DFBd2aIiH1Lrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});